GET http://localhost:3001/api/blogs

POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Reiska ja elämisen taito 1",
  "author": "vILLEgalle & kumppanit",
  "url": "http://villegalle.jee",
  "likes": 669969696
}


DELETE http://localhost:3001/api/blogs/5bfe1c81f3c96b1d18fcc693


GET http://localhost:3001/api/blogs/5bfe1c81f3c96b1d18fcc693

PUT http://localhost:3001/api/blogs/5bfe1c81f3c96b1d18fcc693
content-type: application/json

{
  "title": "Reiska ja Elämän Taito",
  "author": "Reiska McGee",
  "likes": 696969,
  "url": "http://reiskamies.jee"
}

GET http://localhost:3001/api/blogs/5bfe1c81f3c96b1d18fcc693

GET http://localhost:3001/api/users

POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "testi1",
  "name:": "Testinen1",
  "adult": false,
  "password": "justatest!"
}

POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "testi2",
  "name:": "Testinen2",
  "adult": false,
  "password": "justatest2!"
}


POST http://localhost:3001/api/login
content-type: application/json

{ "username": "testi1", "password": "justatest!" }



POST http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMSIsImlkIjoiNWMwYjY2ZWFiOWZkMTEzY2I1MjkxNjhhIiwiaWF0IjoxNTQ0MjU1NDczfQ.hVfDYiQRSA2KhLLtLW2f4_odvb43Oj4kd63KjzZ9Xo8
content-type: application/json

{
  "title": "Reiska ja elämisen taito 2",
  "author": "vILLEgalle & kumppanit",
  "url": "http://villegalle.jee",
  "likes": 669969696
}

POST http://localhost:3001/api/login
content-type: application/json

{ "username": "testi2", "password": "justatest2!" }


POST http://localhost:3001/api/blogs
content-type: application/json

{"author": "Risto Siilasmaa", "likes": 1000, "title": "Paranoidi Optimisti1", "url": "http://ristosiilasmaa.com"}