GET http://localhost:3003/api/blogs

POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Reiska",
  "author": "vILLEgalle",
  "url": "http://villegalle.jee",
  "likes": "999"
}


DELETE http://localhost:3001/api/blogs/5bfe1c81f3c96b1d18fcc693